const animals=[
{id:'bublik',name:'Bagel',type:'dog',breed:'Golden Retriever',price:45000,city:'Moscow',age:'3 months',sex:'Male',tag:'Loves cuddles',color:'#ffe4ca',description:'A little bundle of sunshine. He loves meeting new people, carrying his favorite toy, and falling asleep beside someone. Curious and full of affection.'},
{id:'plush',name:'Plushie',type:'cat',breed:'British Shorthair',price:28000,city:'Saint Petersburg',age:'4 months',sex:'Female',tag:'Purr machine',color:'#eae2fa',description:'A calm, fluffy companion. She loves watching birds from the window and curling up beside a book. A little shy at first, she soon purrs nonstop.'},
{id:'persik',name:'Peach',type:'rabbit',breed:'Dwarf Lop Rabbit',price:7000,city:'Kazan',age:'3 months',sex:'Male',tag:'Ears of joy',color:'#e4eddc',description:'A gentle little explorer with floppy ears. He loves room to roam, fresh greens, and quiet company. He needs a cozy, safe space and a caring person.'}
];
let type='all',onlySaved=false,query='',city='',sort='default';let favorites=new Set();try{const stored=JSON.parse(localStorage.getItem('lapki-favorites')||'[]');if(Array.isArray(stored))favorites=new Set(stored.filter(x=>typeof x==='string'))}catch{}
const $=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const icon=n=>`<svg class="icon" aria-hidden="true"><use href="#${n}"/></svg>`;const money=p=>p===0?'Free to a good home':new Intl.NumberFormat('en-US').format(p)+' ₽';let toastTimer;
function toast(v){$('toast').textContent=v;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3000)}
function filtered(){let a=animals.filter(p=>(type==='all'||p.type===type)&&(!onlySaved||favorites.has(p.id))&&(!city||p.city===city)&&(!query||(p.name+' '+p.breed).toLocaleLowerCase('en-US').includes(query.toLocaleLowerCase('en-US'))));if(sort==='low')a.sort((a,b)=>a.price-b.price);if(sort==='high')a.sort((a,b)=>b.price-a.price);return a}
function render(){const a=filtered();$('pet-grid').innerHTML=a.map((p,i)=>`<article class="pet-card" style="--pet-bg:${p.color};animation-delay:${i*60}ms"><div class="pet-visual"><span class="pet-label">${esc(p.tag)}</span><button class="favorite ${favorites.has(p.id)?'selected':''}" data-favorite="${esc(p.id)}" aria-label="${favorites.has(p.id)?'Remove from favorites':'Add to favorites'}: ${esc(p.name)}" aria-pressed="${favorites.has(p.id)}">${icon('heart')}</button><a href="#pet-${esc(p.id)}" data-detail="${esc(p.id)}" aria-label="Meet ${esc(p.name)}"><img src="assets/${p.type}.webp" alt="${esc(p.name)}, ${esc(p.breed)}" loading="lazy"></a></div><div class="pet-info"><div class="pet-topline"><a href="#pet-${esc(p.id)}" class="pet-name" data-detail="${esc(p.id)}">${esc(p.name)}</a><span class="pet-price">${money(p.price)}</span></div><p class="pet-breed">${esc(p.breed)}</p><div class="pet-meta"><span>${esc(p.age)}</span><span>·</span><span>${esc(p.sex)}</span><span class="pet-city">${icon('pin')}${esc(p.city)}</span></div><a class="pet-detail" data-detail="${esc(p.id)}" href="#pet-${esc(p.id)}">Let's meet ${icon('arrow')}</a></div></article>`).join('');$('empty').hidden=a.length!==0;$('results').textContent=onlySaved?'Favorites: '+a.length:'Pets found: '+a.length;$('saved-count').textContent=animals.filter(p=>favorites.has(p.id)).length;$('saved').classList.toggle('on',onlySaved);$('saved').setAttribute('aria-pressed',String(onlySaved));document.querySelectorAll('[data-type]').forEach(b=>{const active=b.dataset.type===type;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});return a}
function favorite(id){if(favorites.has(id)){favorites.delete(id);toast('Removed from favorites')}else{favorites.add(id);toast('Saved to favorites ♡')}try{localStorage.setItem('lapki-favorites',JSON.stringify([...favorites]))}catch{}render();const b=$('detail-content').querySelector('[data-favorite]');if(b){b.textContent=favorites.has(id)?'Remove from favorites':'Save to favorites';b.setAttribute('aria-pressed',String(favorites.has(id)))}}
function showPet(id){const p=animals.find(x=>x.id===id);if(!p)return false;$('detail-content').innerHTML=`<div class="detail-layout" style="--pet-bg:${p.color}"><div class="detail-image"><img src="assets/${p.type}.webp" alt="${esc(p.name)}"></div><div class="detail-copy"><span class="section-kicker">${esc(p.tag)}</span><h2>${esc(p.name)}</h2><p>${esc(p.breed)}</p><div class="detail-facts"><span>${esc(p.age)}</span><span>${esc(p.sex)}</span><span>${esc(p.city)}</span></div><p>${esc(p.description)}</p><div class="detail-price">${money(p.price)}</div><button class="button" data-favorite="${esc(p.id)}" aria-pressed="${favorites.has(p.id)}">${favorites.has(p.id)?'Remove from favorites':'Save to favorites'}</button><p class="demo-note">Sample listing. Owner contact and purchases are unavailable in this demo.</p></div></div>`;$('detail').showModal();return true}
function reset(){type='all';onlySaved=false;query='';city='';sort='default';$('query').value='';$('city').value='';$('sort').value='default';render()}
document.addEventListener('click',e=>{const f=e.target.closest('[data-favorite]');if(f){e.preventDefault();favorite(f.dataset.favorite);return}const d=e.target.closest('[data-detail]');if(d){e.preventDefault();showPet(d.dataset.detail);return}const c=e.target.closest('[data-type]');if(c){type=c.dataset.type;render()}});
$('search-form').addEventListener('submit',e=>{e.preventDefault();query=$('query').value.trim();city=$('city').value;render();$('catalog').scrollIntoView({behavior:'smooth'})});$('query').addEventListener('input',()=>{query=$('query').value.trim();render()});$('city').addEventListener('change',()=>{city=$('city').value;render()});$('sort').addEventListener('change',()=>{sort=$('sort').value;render()});$('saved').addEventListener('click',()=>{onlySaved=!onlySaved;render();$('catalog').scrollIntoView({behavior:'smooth'})});$('reset').onclick=reset;
for(const d of document.querySelectorAll('dialog')){d.querySelector('.close').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})}
for(const id of ['sell','sell-bottom'])$(id).onclick=()=>$('sell-dialog').showModal();$('how').onclick=()=>$('info-dialog').showModal();$('listing-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const name=String(f.get('name')).trim(),breed=String(f.get('breed')).trim(),description=String(f.get('description')).trim(),kind=String(f.get('type')),price=Number(f.get('price'));if(!name||!breed||!description||!['dog','cat','rabbit'].includes(kind)||!Number.isFinite(price)||price<0||price>1000000)return;animals.unshift({id:'demo-'+Date.now(),name,breed,description,type:kind,price,city:String(f.get('city')),age:'Age not specified',sex:'Sex not specified',tag:'New arrival',color:{dog:'#ffe4ca',cat:'#eae2fa',rabbit:'#e4eddc'}[kind]});reset();$('sell-dialog').close();e.target.reset();toast('Sample listing added until you refresh the page');$('catalog').scrollIntoView({behavior:'smooth'})});render();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'filter_pet_catalog',title:'Find pets',description:'Set visible demo catalog filters and return matching pets.',inputSchema:{type:'object',properties:{type:{type:'string',enum:['all','dog','cat','rabbit']},query:{type:'string'},city:{type:'string',enum:['','Moscow','Saint Petersburg','Kazan']}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['type','query','city'].includes(k)))throw Error('Invalid parameters');if(input.type!==undefined&&!['all','dog','cat','rabbit'].includes(input.type))throw Error('Unknown pet type');if(input.city!==undefined&&!['','Moscow','Saint Petersburg','Kazan'].includes(input.city))throw Error('Unknown city');if(input.query!==undefined&&typeof input.query!=='string')throw Error('Search query must be a string');type=input.type??'all';query=input.query??'';city=input.city??'';onlySaved=false;$('query').value=query;$('city').value=city;return {pets:render().map(({id,name,breed,price,city})=>({id,name,breed,price,city}))}}} ,{signal:lifecycle.signal})).catch(()=>{})}catch{}}
